build:
  main:
    image: golang
    commands:
      - go get
      - GOOS=linux GOARCH=amd64 ./build.sh
    #when:
    #  branch: master
      
publish:
  s3:
    acl: authenticated-read
    region: "us-east-1"
    bucket: "peoplenet-custom-tools"
    access_key: $$PEOPLENET_CI_AWS_KEY_ID
    secret_key: $$PEOPLENET_CI_AWS_SECRET_KEY
    source: build
    target: /terraform