build:
  main:
    image: golang
    commands:
      - mkdir -p build
      - go get
      - go build -o build/terraform-provider-kapacitor
      - tar -zcvf terraform-provider-kapacitor-linux-amd64.tar.gz build/terraform-provider-kapacitor
    #when:
    #  branch: master
      
publish:
  s3:
    acl: authenticated-read
    region: "us-east-1"
    bucket: "peoplenet-custom-tools"
    access_key: $$PEOPLENET_CI_AWS_KEY_ID
    secret_key: $$PEOPLENET_CI_AWS_SECRET_KEY
    source: terraform-provider-kapacitor-linux-amd64.tar.gz
    target: /terraform-provider-kapacitor/terraform-provider-kapacitor-linux-amd64.tar.gz